name: my first workflow

on: push

jobs:
    first_job:
        name: job execution testing
        runs-on: ubuntu-latest
        steps:
            
            - name: checkout_Repo
              uses: actions/checkout@v4

            - name: welcome message
              run: |
                echo "my first github action job execution"
                ls -lrta
                cat README.md
            - name: Generate ASCII Network
              run: cowsay -f dragon "Run for cover, I am a dragon ......... RAWR" >> dragon.txt

            # - name: list the current directory
            #   run: ls
            
            # - name: read the file 
            #   run: cat README.md