name: Generate ASCII Artwork
on: push

jobs:
    Build-job-1:
        runs-on: ubuntu-latest
        steps:
        - name: Install the cowsay library
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay command
          run: cowsay -f dragon "I Am A DRAGON...... DRAR" > dragon.txt
        - name: slep for 30s
          run: sleep 30
        - name: Upload Artifcat
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt
    
    Test-Job-2:
        runs-on: ubuntu-latest
        steps:
        - name: Download Artifcat
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: Check the text
          run: grep -i "dragon" dragon.txt
        needs: Build-job-1
    
    Deploy-Job-3:
        runs-on: ubuntu-latest
        steps:
        - name: Download Artifcat
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: Read the text file
          run: cat dragon.txt
        - name: Deploy
          run: echo "Deploying ................"
        needs: [Build-job-1,Test-Job-2]

        

    # ascii_job:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: checkout Repo
    #       uses: actions/checkout@v4
        
    #     - name: list the root directory
    #       run: ls -lrta
        
    #     - name: execute the script for ascii generation
    #       run: |
    #         chmod +x ascii-script.sh
    #         ./ascii-script.sh
        
        # - name: install cowasy library
        #   run: sudo apt-get install cowsay -y
        # - name: run the cowasy command
        #   run: cowsay -f dragon "Run for cover, I am a DRAGON ....... RAWD" >> dragon.txt
        # - name: list the repo
        #   run: ls -lrta
        # - name: test-file existing
        #   run: grep -i "dragon" dragon.txt
        # - name: read the file
        #   run: cat dragon.txt

