name: Installing Python

on: [push]

jobs:
  build:
    strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, macos-14, windows-latest]
            py-version: [3.10,3.11,3.12]
    runs-on: ${{matrix.os}}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.py-version}}
    - run: python --version
    # - name: Verify Python Version
    #   run: python --version
    
        