name: Exploring varibale & secrets

# on: push
on:
  workflow_dispatch:
env:
    CONTAINER_REGISTRY: docker.io
    # DOCKER_USERNAME: sureshsk
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        #timeout-minutes: 1 #job level timeout
        steps:
        - name: docker build
          timeout-minutes: 1 #steps level timeout
          run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
        - name: docker login
        #   env:
        #     DOCKER_PASSWORD: PassWord
          run: echo docker login --username ${{ vars.DOCKER_USERNAME}} --passowrd ${{ secrets.DOCKER_PASSWORD }}
        - name: docker publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
    
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        timeout-minutes: 1
        concurrency:
            group: production-deployment
            cancel-in-progress: false
        steps:
        - name: docker run
          run: |
            echo docker run -d -p 8000:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
            sleep 600s



