name: Exploring Workflow filters and Activities

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - '!feature/*'
    pull_request:
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: run a samplejob
              run: echo this workflow/job/step is executed for event type - ${{github.event_name}}

